### ISSUE TITLE
Value Check is buggy

### ISSUE THREAD

**Issue by smiddy** [benpruitt/tecancavro#6]
Please have a look at

https://github.com/benpruitt/tecancavro/blob/master/tecancavro/models.py#L472-L481

The number are not coherent.

**Comment by benpruitt** [comment]
Thanks for catching this discrepancy. I see that the ValueError strings are incorrect, but are you also having issues with the actual check value ranges being off?

**Comment by smiddy** [comment]
I inted to write a new model class for our Cavro XLP 6000 and just spotted the typo. I keep you updated if I find anything else.

**Comment by benpruitt** [comment]
Ok great, thanks again.
